language: ruby
cache: bundler # caching bundler gem packages will speed up build
rvm:
  - 2.4.1
branches:
  only:
    - master
install: bundle install
script:
  - bundle exec github-pages versions
  - bundle exec rake test

addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors with html-proofer

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

exclude: [vendor]

sudo: false # route your build to the container-based infrastructure for a faster build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false
